"""empty message

Revision ID: 44f546a8668f
Revises: c6bca144cd3e
Create Date: 2024-07-30 15:57:05.628543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f546a8668f'
down_revision = 'c6bca144cd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_firs_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_firs_name_key', ['firs_name'])

    # ### end Alembic commands ###
